apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocis
spec:
  template:
    spec:
      containers:
        - name: ocis
          env:
            - name: IDM_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: idm
                  name: password
            - name: OCIS_OIDC_ISSUER
              valueFrom:
                secretKeyRef:
                  key: oidc_url
                  name: oidc_data
