apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocis-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: freenas-iscsi-csi
  resources:
    requests:
      storage: 100G
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocis-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: freenas-nfs-csi
  resources:
    requests:
      storage: 1G
status: {}
