apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ocis
  name: ocis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocis
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ocis
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - args:
            - -c
            - ocis init || true; ocis server
          command:
            - /bin/sh
          env:
            - name: IDM_CREATE_DEMO_USERS
              value: "false"
            - name: NOTIFICATIONS_SMTP_HOST
              value: smtp.example.com
            - name: NOTIFICATIONS_SMTP_INSECURE
              value: "false"
            - name: NOTIFICATIONS_SMTP_PORT
              value: "465"
            - name: NOTIFICATIONS_SMTP_SENDER
              value: oCIS notifications <notifications@ocis.example.com>
            - name: NOTIFICATIONS_SMTP_USERNAME
              value: me@example.com
            - name: GATEWAY_GRPC_ADDR
              value: "0.0.0.0:9142"
            - name: OCIS_INSECURE
              value: "false"
            - name: OCIS_LOG_COLOR
              value: "false"
            - name: OCIS_LOG_LEVEL
              value: info
            - name: OCIS_URL
              value: https://ocis.example.com
            - name: PROXY_ENABLE_BASIC_AUTH
              value: "false"
            - name: PROXY_TLS
              value: "false"
            - name: PROXY_AUTOPROVISION_ACCOUNTS
              value: "true"
            - name: PROXY_OIDC_REWRITE_WELLKNOWN
              value: "true"
            - name: WEB_OIDC_CLIENT_ID
              value: web
            - name: PROXY_ROLE_ASSIGNMENT_DRIVER
              value: "default"
            - name: PROXY_USER_OIDC_CLAIM
              value: "preferred_username"
            - name: PROXY_USER_CS3_CLAIM
              value: "username"
            - name: OCIS_EXCLUDE_RUN_SERVICES
              value: "idp"
            - name: GRAPH_USERNAME_MATCH
              value: "none"
            - name: GRAPH_ASSIGN_DEFAULT_USER_ROLE
              value: "false"
          image: owncloud/ocis:2.0.0
          name: ocis
          resources: {}
          volumeMounts:
            - mountPath: /etc/ocis
              name: ocis-config
            - mountPath: /var/lib/ocis
              name: ocis-data
      restartPolicy: Always
      volumes:
        - name: ocis-config
          persistentVolumeClaim:
            claimName: ocis-config
        - name: ocis-data
          persistentVolumeClaim:
            claimName: ocis-data
status: {}
